### ISSUE TITLE
No applicable method for code/concept functions

### ISSUE THREAD

**Issue by JamesAFarrell** [rcfgroup/clinconcept#5]
Hi Rob,
Thanks for creating this very useful package. I've been following the vignette [here](https://arxiv.org/pdf/2002.11431.pdf) but have run into issues using functions related to concepts or codes.
For example,
`asthma = search_concepts(dict, term == "Asthma")`
returns the error:
`Error in UseMethod("search_concepts") : 
  no applicable method for 'search_concepts' applied to an object of class "c('NHSReadV3', 'clinconcept')"`

When I do `methods("search_concepts")` I get the message `no methods found`. I have similar problems with `get_parent_codes` and `get_child_codes`. Do you know what might be causing this? Thanks!

**Comment by rcfree** [comment]
Hi James,

Thank you for your kind comments.

I had a look at this problem and it looks like it's a packaging issue and should be fairly straightforward to resolve.

I will see if I can fix this tomorrow and push a new version. I'll comment again once it's done.

**Comment by rcfree** [comment]
I have pushed these changes. Please could you see if reinstalling fixes the issue.

**Comment by JamesAFarrell** [comment]
Thanks Rob, it works perfectly now!
